import { z } from 'zod';
import { IdSchema, IsoTimestampSchema } from './ids';
import { jsonColumnSchema } from './json';
import { AutonomySchema, RoleDeliverableKindSchema } from './enums';
import { UsdMicrosSchema } from './money';

const StringArraySchema = z.array(z.string());

// §11.3 (M6) owns the real tool-pattern grammar; M1 only needs "array of
// pattern strings" to model the column correctly.
const ToolPatternArraySchema = z.array(z.string());

export const RoleSchema = z.object({
  id: IdSchema,
  key: z.string().min(1),
  // Generated by the DB as `pack_id || ':' || key` (finding #2 — the FK
  // from employees.role_key needs a genuinely unique target column, and
  // §5.1 already says roles are addressed as `pack:key` everywhere else).
  full_key: z.string().min(1),
  department_key: z.string().min(1),
  pack_id: z.string().min(1),
  priority: z.number().int(),
  version: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  system_prompt_path: z.string().min(1),
  skills: jsonColumnSchema(StringArraySchema),
  deliverable_types: jsonColumnSchema(z.array(RoleDeliverableKindSchema)),
  engine_preference: jsonColumnSchema(StringArraySchema),
  model_preference: jsonColumnSchema(StringArraySchema).nullable(),
  tools_allow: jsonColumnSchema(ToolPatternArraySchema),
  tools_deny: jsonColumnSchema(ToolPatternArraySchema),
  network_allow: jsonColumnSchema(StringArraySchema),
  memory_scopes: jsonColumnSchema(StringArraySchema),
  autonomy_default: AutonomySchema,
  max_turns: z.number().int(),
  max_attempts: z.number().int(),
  wall_clock_timeout_s: z.number().int(),
  budget_usd_micros: UsdMicrosSchema.nullable(),
  sprite_key: z.string().min(1),
  role_options: jsonColumnSchema(z.record(z.unknown())),
  enabled: z.coerce.boolean(),
  // Not in §5.1's own listing; §5.0's blanket rule applies (mutable via
  // `enabled`).
  created_at: IsoTimestampSchema,
  updated_at: IsoTimestampSchema,
});
export type Role = z.infer<typeof RoleSchema>;

export const NewRoleInputSchema = z.object({
  key: z.string().min(1),
  department_key: z.string().min(1),
  pack_id: z.string().min(1),
  priority: z.number().int().default(50),
  version: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  system_prompt_path: z.string().min(1),
  skills: StringArraySchema,
  deliverable_types: z.array(RoleDeliverableKindSchema),
  engine_preference: StringArraySchema,
  model_preference: StringArraySchema.nullable().default(null),
  tools_allow: ToolPatternArraySchema,
  tools_deny: ToolPatternArraySchema,
  network_allow: StringArraySchema.default([]),
  memory_scopes: StringArraySchema,
  autonomy_default: AutonomySchema,
  max_turns: z.number().int().default(40),
  max_attempts: z.number().int().default(2),
  wall_clock_timeout_s: z.number().int().default(2400),
  budget_usd_micros: UsdMicrosSchema.nullable().default(null),
  sprite_key: z.string().min(1),
  role_options: z.record(z.unknown()).default({}),
  enabled: z.boolean().default(true),
});
export type NewRoleInput = z.infer<typeof NewRoleInputSchema>;
