import { z } from 'zod';
import { IdSchema, IsoTimestampSchema } from './ids';
import { jsonColumnSchema } from './json';
import { AutonomySchema, ModelTierSchema, RoleDeliverableKindSchema } from './enums';
import { UsdMicrosSchema } from './money';
import { RoleEngineOptionsSchema } from './engineOptions';
import { RoleInputKindSchema } from './pack';

/**
 * §6.5's `reports` — one shape the pack author edits as a unit, stored as
 * one JSON column rather than two, because the Core never queries either
 * half independently. Defaulted to empty strings for rows written before
 * migration 0006 gave the column a home.
 */
const RoleReportsSchema = z.object({
  on_complete: z.string().default(''),
  on_block: z.string().default(''),
});

const StringArraySchema = z.array(z.string());

/**
 * §7.5/§6.5: "Roles declare abstract tiers, not model names" — an ordered
 * preference list of `fast`/`balanced`/`capable`, resolved to a concrete
 * model id per engine via `settings.engines.modelTiers` at spawn time.
 *
 * AUDIT #1 settled the standing "spec and schema disagree" question: they
 * do not. `model_preference` IS §7.5's tier column (§6.5's own example is
 * `model_preference: [balanced, capable]  # abstract tiers`), and
 * `model_tier` is not a spec term anywhere. What was genuinely wrong is
 * that this validated as a bare `string[]`, so a role could carry a
 * concrete model name — the exact thing §7.5 forbids — and nothing
 * objected.
 */
const ModelTierArraySchema = z.array(ModelTierSchema);

// §11.3 (M6) owns the real tool-pattern grammar; M1 only needs "array of
// pattern strings" to model the column correctly.
const ToolPatternArraySchema = z.array(z.string());

export const RoleSchema = z.object({
  id: IdSchema,
  key: z.string().min(1),
  // Generated by the DB as `pack_id || ':' || key` (finding #2 — the FK
  // from employees.role_key needs a genuinely unique target column, and
  // §5.1 already says roles are addressed as `pack:key` everywhere else).
  full_key: z.string().min(1),
  department_key: z.string().min(1),
  pack_id: z.string().min(1),
  priority: z.number().int(),
  version: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  system_prompt_path: z.string().min(1),
  // Added at M7 (migration 0006) — in §6.5's role.yaml since the start,
  // but with no §5.1 column to land in until packs could actually be
  // installed. See the migration for why all four arrived together.
  shared_prompts: jsonColumnSchema(StringArraySchema),
  skills: jsonColumnSchema(StringArraySchema),
  deliverable_types: jsonColumnSchema(z.array(RoleDeliverableKindSchema)),
  input_types: jsonColumnSchema(z.array(RoleInputKindSchema)),
  engine_preference: jsonColumnSchema(StringArraySchema),
  model_preference: jsonColumnSchema(ModelTierArraySchema).nullable(),
  tools_allow: jsonColumnSchema(ToolPatternArraySchema),
  tools_deny: jsonColumnSchema(ToolPatternArraySchema),
  network_allow: jsonColumnSchema(StringArraySchema),
  memory_scopes: jsonColumnSchema(StringArraySchema),
  memory_budget_tokens: z.number().int(),
  autonomy_default: AutonomySchema,
  max_turns: z.number().int(),
  max_attempts: z.number().int(),
  wall_clock_timeout_s: z.number().int(),
  budget_usd_micros: UsdMicrosSchema.nullable(),
  escalate_when: jsonColumnSchema(StringArraySchema),
  reports: jsonColumnSchema(RoleReportsSchema),
  sprite_key: z.string().min(1),
  role_options: jsonColumnSchema(z.record(z.unknown())),
  engine_options: jsonColumnSchema(RoleEngineOptionsSchema).nullable(),
  enabled: z.coerce.boolean(),
  // Not in §5.1's own listing; §5.0's blanket rule applies (mutable via
  // `enabled`).
  created_at: IsoTimestampSchema,
  updated_at: IsoTimestampSchema,
});
export type Role = z.infer<typeof RoleSchema>;

export const NewRoleInputSchema = z.object({
  key: z.string().min(1),
  department_key: z.string().min(1),
  pack_id: z.string().min(1),
  priority: z.number().int().default(50),
  version: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  system_prompt_path: z.string().min(1),
  shared_prompts: StringArraySchema.default([]),
  skills: StringArraySchema,
  deliverable_types: z.array(RoleDeliverableKindSchema),
  input_types: z.array(RoleInputKindSchema).default([]),
  engine_preference: StringArraySchema,
  model_preference: ModelTierArraySchema.nullable().default(null),
  tools_allow: ToolPatternArraySchema,
  tools_deny: ToolPatternArraySchema,
  network_allow: StringArraySchema.default([]),
  memory_scopes: StringArraySchema,
  memory_budget_tokens: z.number().int().positive().default(8000),
  autonomy_default: AutonomySchema,
  max_turns: z.number().int().default(40),
  max_attempts: z.number().int().default(2),
  wall_clock_timeout_s: z.number().int().default(2400),
  budget_usd_micros: UsdMicrosSchema.nullable().default(null),
  escalate_when: StringArraySchema.default([]),
  reports: RoleReportsSchema.default({ on_complete: '', on_block: '' }),
  sprite_key: z.string().min(1),
  role_options: z.record(z.unknown()).default({}),
  // Loosely typed here on purpose — insertRole() validates this against the
  // specific schema for engine_preference[0] (engineOptionsSchemaFor) before
  // it's ever persisted, since that's the one call site that has both this
  // value and the deciding engine key in hand at once (see engineOptions.ts).
  engine_options: z.record(z.unknown()).nullable().default(null),
  enabled: z.boolean().default(true),
});
export type NewRoleInput = z.input<typeof NewRoleInputSchema>;
